### PR TITLE
VE 1915: Add support for dynamic configuration

### PR DESCRIPTION
**Pull request by pauloslund**

### CODE REVIEW

**Comment by inez** [comment]
Could you split it into two prs? One for just bringing newest version of vanilla parsois (and it does not have to be reviewed) and another one for your actual changes to support dynamic configuration.

**Comment by inez** [comment]
Also, please take a look into failing Travis ci jobs.

**Comment by pauloslund** [comment]
Can do

**Comment by inez** [comment]
Btw. Given that upstream repo name has changed - we could just fork it to wikia a new repo.

**Comment by pauloslund** [comment]
so just fork `mediawiki/parsoid` to `wikia/parsoid`?

**Pull request closed without merging**
